In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
#creating dataframes using just closing prices like FRED's format'

sp500 = pd.read_csv('SP500.csv', usecols=['Date','Close'], index_col='Date').round({'Close':2})
sp500.index = pd.to_datetime(sp500.index)

dxy = pd.read_csv('DXY.csv', usecols=['Date','Close'], index_col='Date').round({'Close':2})
dxy.index = pd.to_datetime(dxy.index)

us02y = pd.read_csv('US02Y.csv', usecols=['Date','Close'], index_col='Date')
us02y.index = pd.to_datetime(us02y.index)

vix = pd.read_csv('VIX.csv', usecols=['Date','Close'], index_col='Date').round({'Close':2})
vix.index = pd.to_datetime(vix.index)

In [3]:
market_df = sp500.merge(dxy, left_index=True, right_index=True, how='inner')
market_df = market_df.merge(us02y, left_index=True, right_index=True, how='inner')
market_df = market_df.merge(vix, left_index=True, right_index=True, how='inner', suffixes=('_w','_z'))

market_df = market_df.rename(columns={
    'Close_x':'SP500',
    'Close_y':'DXY',
    'Close_w':'US02Y',
    'Close_z':'VIX'
})

market_df.head()

             SP500    DXY  US02Y    VIX
Date
1990-01-02  359.69  94.29   7.87  17.24
1990-01-03  358.76  94.42   7.94  18.19
1990-01-04  355.67  92.52   7.92  19.22
1990-01-05  352.20  92.85   7.90  20.11
1990-01-08  353.79  92.05   7.90  20.26

In [4]:
market_df.isna().sum()

SP500     0
DXY       0
US02Y    73
VIX       0
dtype: int64

In [5]:
market_df = market_df.dropna()
print(market_df.isna().sum())
print(market_df.shape)

SP500    0
DXY      0
US02Y    0
VIX      0
dtype: int64
(9111, 4)

In [6]:
#1 week = 5 closes
#1 month = 21 closes
#6 months = 126 closes
# 1 year = 252 closes

log_sp500 = np.log(market_df['SP500'])

market_df['fut_returns_5d'] = (log_sp500.shift(-5) - log_sp500).round(2)
market_df['fut_returns_21d'] = (log_sp500.shift(-21) - log_sp500).round(2)
market_df['fut_returns_126d'] = (log_sp500.shift(-126) - log_sp500).round(2)
market_df['fut_returns_252d'] = (log_sp500.shift(-252) - log_sp500).round(2)

market_df.head()

,SP500,DXY,US02Y,VIX,fut_returns_5d,fut_returns_21d,fut_returns_126d,fut_returns_252d
Date,,,,,,,,
1990-01-02,359.69,94.29,7.87,17.24,-0.03,-0.09,0.00,-0.11
1990-01-03,358.76,94.42,7.94,18.19,-0.03,-0.08,-0.01,-0.13
1990-01-04,355.67,92.52,7.92,19.22,-0.02,-0.07,0.01,-0.12
1990-01-05,352.20,92.85,7.90,20.11,-0.04,-0.07,0.02,-0.12
1990-01-08,353.79,92.05,7.90,20.26,-0.04,-0.06,0.01,-0.12

In [7]:
log_vix = np.log(market_df['VIX'])

market_df['delta_vix_5d'] = (log_vix - log_vix.shift(5)).round(2)
market_df['delta_vix_21d'] = (log_vix - log_vix.shift(21)).round(2)
market_df['delta_vix_126d'] = (log_vix - log_vix.shift(126)).round(2)
market_df['delta_vix_252d'] = (log_vix - log_vix.shift(252)).round(2)

log_dxy = np.log(market_df['DXY'])

market_df['delta_dxy_5d'] = (log_dxy - log_dxy.shift(5)).round(2)
market_df['delta_dxy_21d'] = (log_dxy - log_dxy.shift(21)).round(2)
market_df['delta_dxy_126d'] = (log_dxy - log_dxy.shift(126)).round(2)
market_df['delta_dxy_252d'] = (log_dxy - log_dxy.shift(252)).round(2)

market_df['delta_US02Y_5d'] = (market_df['US02Y'] - market_df['US02Y'].shift(5)).round(2)
market_df['delta_US02Y_21d'] = (market_df['US02Y'] - market_df['US02Y'].shift(21)).round(2)
market_df['delta_US02Y_126d'] = (market_df['US02Y'] - market_df['US02Y'].shift(126)).round(2)
market_df['delta_US02Y_252d'] = (market_df['US02Y'] - market_df['US02Y'].shift(252)).round(2)

market_df.head(10)

,SP500,DXY,US02Y,VIX,fut_returns_5d,fut_returns_21d,fut_returns_126d,fut_returns_252d,delta_vix_5d,delta_vix_21d,delta_vix_126d,delta_vix_252d,delta_dxy_5d,delta_dxy_21d,delta_dxy_126d,delta_dxy_252d,delta_US02Y_5d,delta_US02Y_21d,delta_US02Y_126d,delta_US02Y_252d
Date,,,,,,,,,,,,,,,,,,,,
1990-01-02,359.69,94.29,7.87,17.24,-0.03,-0.09,0.00,-0.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-03,358.76,94.42,7.94,18.19,-0.03,-0.08,-0.01,-0.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-04,355.67,92.52,7.92,19.22,-0.02,-0.07,0.01,-0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-05,352.20,92.85,7.90,20.11,-0.04,-0.07,0.02,-0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-08,353.79,92.05,7.90,20.26,-0.04,-0.06,0.01,-0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-09,349.62,92.35,7.91,22.20,-0.04,-0.05,0.03,-0.10,0.25,NaN,NaN,NaN,-0.02,NaN,NaN,NaN,0.04,NaN,NaN,NaN
1990-01-10,347.31,92.39,7.91,22.44,-0.03,-0.04,0.05,-0.11,0.21,NaN,NaN,NaN,-0.02,NaN,NaN,NaN,-0.03,NaN,NaN,NaN
1990-01-11,348.53,92.40,7.91,20.05,-0.03,-0.05,0.05,-0.11,0.04,NaN,NaN,NaN,-0.00,NaN,NaN,NaN,-0.01,NaN,NaN,NaN
1990-01-12,339.93,92.43,7.93,24.64,-0.03,-0.03,0.08,-0.07,0.20,NaN,NaN,NaN,-0.00,NaN,NaN,NaN,0.03,NaN,NaN,NaN
1990-01-16,340.75,92.94,8.10,24.18,-0.03,-0.03,0.08,-0.04,0.18,NaN,NaN,NaN,0.01,NaN,NaN,NaN,0.20,NaN,NaN,NaN

In [8]:
market_df = market_df.dropna()
market_df.shape

(8607, 20)

In [ ]:
market_df.describe()
#returns following a gaussian distribuiton slightly positive assimetric
#5d = 0.18%
#21d = 0.72%
#126d = 4.2%
#252d = 8.46%

,SP500,DXY,US02Y,VIX,fut_returns_5d,fut_returns_21d,fut_returns_126d,fut_returns_252d,delta_vix_5d,delta_vix_21d,delta_vix_126d,delta_vix_252d,delta_dxy_5d,delta_dxy_21d,delta_dxy_126d,delta_dxy_252d,delta_US02Y_5d,delta_US02Y_21d,delta_US02Y_126d,delta_US02Y_252d
count,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000,8607.000000
mean,1789.384086,92.507725,3.093610,19.379054,0.001775,0.007151,0.042235,0.084629,-0.000123,-0.000569,-0.003187,-0.006189,0.000055,0.000448,0.002941,0.004540,-0.001871,-0.008118,-0.055618,-0.119138
std,1324.258246,10.235294,2.155515,7.864775,0.024002,0.046009,0.108258,0.160030,0.133983,0.218011,0.339977,0.393786,0.011604,0.023379,0.058400,0.078607,0.123143,0.264166,0.806748,1.301445
min,311.490000,71.330000,0.090000,9.140000,-0.200000,-0.400000,-0.630000,-0.680000,-0.630000,-0.840000,-1.200000,-1.400000,-0.080000,-0.100000,-0.150000,-0.200000,-1.120000,-1.230000,-2.790000,-3.620000
25%,963.065000,84.320000,0.890000,13.770000,-0.010000,-0.010000,-0.000000,0.030000,-0.080000,-0.130000,-0.220000,-0.250000,-0.010000,-0.010000,-0.040000,-0.050000,-0.060000,-0.140000,-0.480000,-1.000000
50%,1309.930000,92.650000,2.990000,17.500000,0.000000,0.010000,0.050000,0.110000,-0.010000,-0.020000,-0.030000,-0.020000,0.000000,0.000000,0.000000,0.010000,0.000000,0.000000,-0.010000,-0.040000
75%,2182.430000,99.155000,4.910000,22.655000,0.010000,0.030000,0.110000,0.180000,0.070000,0.110000,0.180000,0.240000,0.010000,0.020000,0.040000,0.060000,0.060000,0.130000,0.390000,0.570000
max,6144.150000,120.900000,7.740000,82.690000,0.170000,0.220000,0.410000,0.560000,1.140000,1.770000,1.730000,1.820000,0.060000,0.120000,0.200000,0.230000,0.700000,1.050000,2.790000,4.260000

In [24]:
baseline = pd.DataFrame(market_df[['fut_returns_5d','fut_returns_21d','fut_returns_126d','fut_returns_252d']].describe())

baseline['sp_%_positive_periods_5d'] = (market_df['fut_returns_5d'] > 0).mean()
baseline['sp_%_positive_periods_21d'] = (market_df['fut_returns_21d'] > 0).mean()
baseline['sp_%_positive_periods_126d'] = (market_df['fut_returns_126d'] > 0).mean()
baseline['sp_%_positive_periods_252d'] = (market_df['fut_returns_252d'] > 0).mean()

baseline

#as long the observation period gets, more likely it is to get positive returns from sp500

,fut_returns_5d,fut_returns_21d,fut_returns_126d,fut_returns_252d,sp_%_positive_periods_5d,sp_%_positive_periods_21d,sp_%_positive_periods_126d,sp_%_positive_periods_252d
count,8607.000000,8607.000000,8607.000000,8607.000000,0.462995,0.586848,0.733124,0.794237
mean,0.001775,0.007151,0.042235,0.084629,0.462995,0.586848,0.733124,0.794237
std,0.024002,0.046009,0.108258,0.160030,0.462995,0.586848,0.733124,0.794237
min,-0.200000,-0.400000,-0.630000,-0.680000,0.462995,0.586848,0.733124,0.794237
25%,-0.010000,-0.010000,-0.000000,0.030000,0.462995,0.586848,0.733124,0.794237
50%,0.000000,0.010000,0.050000,0.110000,0.462995,0.586848,0.733124,0.794237
75%,0.010000,0.030000,0.110000,0.180000,0.462995,0.586848,0.733124,0.794237
max,0.170000,0.220000,0.410000,0.560000,0.462995,0.586848,0.733124,0.794237

In [31]:
windows = ['fut_returns_5d','fut_returns_21d','fut_returns_126d','fut_returns_252d']

def combination(dataframe, variable_column_1, variable_column_2, fut_returns):
    #DXY AND VIX UP
    var_1_up_var_2_up_5d = (dataframe[variable_column_1] > 0) & (dataframe[variable_column_2] > 0)
    

    results = dataframe.loc[var_1_up_var_2_up_5d, fut_returns].describe()

    return results
combination(market_df, 'delta_dxy_5d','delta_vix_5d',windows)

       fut_returns_5d  fut_returns_21d  fut_returns_126d  fut_returns_252d
count     1250.000000      1250.000000       1250.000000       1250.000000
mean         0.002464         0.007952          0.039824          0.090536
std          0.029433         0.053251          0.117845          0.152000
min         -0.200000        -0.380000         -0.630000         -0.520000
25%         -0.010000        -0.020000         -0.010000          0.020000
50%          0.000000         0.010000          0.050000          0.110000
75%          0.020000         0.040000          0.107500          0.190000
max          0.170000         0.210000          0.380000          0.520000